
rgchat:
  build: .
  ports:
    - "3000"
  links:
    - db

db:
  image: mongo
  volumes:
    - /data/db:/data/db
  ports:
    - "27017"

jenkins:
  image: jenkins:latest
  volumes:
    - /home/jabiers/jenkins:/var/jenkins_home
  ports:
    - "8080"
    - "50000:50000"

haproxy:
  image: haproxy
  volumes:
    - /home/jabiers/conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  links:
    - "jenkins:jenkins"
    - "rgchat:rgchat"
  ports:
    - "80:80"
  expose:
    - "80"
